name: Build C# Console App

on:
  workflow_dispatch:          # Allows manual trigger from GitHub UI
  push:
    branches: [ main ]        # Change to master if your repo uses master
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x  # Change to your .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    # Optional - if you have test projects:
    - name: Run Tests
      run: dotnet test --no-build --verbosity normal
